---
- name: Deploy web servers on VM1 and VM2
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom index.html
      copy:
        content: "Hello World from SJSU-{{ inventory_hostname[-1] }}"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Configure Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 8080'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
